volumes:
  db-data:

services:
  crawler:
    image: ghcr.io/lee98064/crawler-notify:latest
    volumes:
      - db-data:/app/db
    ports:
      - "5000:5000"
    environment:
      TELEGRAM_BOT_TOKEN: TELEGRAM_BOT_TOKEN
      TELEGRAM_CHAT_ID: TELEGRAM_CHAT_ID
