name: Build

on:
  workflow_call:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  initial:
    runs-on: ubuntu-latest

    outputs:
      commit: ${{ steps.commit.outputs.shortened }}

    steps:
      ## Should be aware of the GITHUB_SHA of pull_request events
      ## https://github.com/orgs/community/discussions/26325
      - name: Generate shortened commit SHA for image tag
        id: commit
        run: |
          COMMIT_SHA=${{ github.event.pull_request.head.sha || github.sha }}
          echo "::set-output name=shortened::${COMMIT_SHA:0:7}"
      - name: Print output
        run: |
          echo "shortened=${{ steps.commit.outputs.shortened }}"

  build-docker-image:
    strategy:
      matrix:
        modules:
          - crawler-notify
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image - ${{ matrix.modules }}
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.modules }}
          file: ./${{ matrix.modules }}/Dockerfile
          push: true
          tags: |
            ghcr.io/lee98064/${{ matrix.modules }}:${{ needs.initial.outputs.commit }}
            ghcr.io/lee98064/${{ matrix.modules }}:latest
          labels: ${{ steps.meta.outputs.labels }}
    needs: initial
